#!/bin/bash
### BEGIN INIT INFO
# Provides:          restart_enigmabox
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: restart_enigmabox
# Description:       dummy service for restarting the box
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

do_restart()
{
    sleep 30
    reboot
}

do_status()
{
    echo "running"
}

case "$1" in
  start)
    exit 0
    ;;
  stop)
    exit 0
    ;;
  restart)
    do_restart
    ;;
  status)
    do_status
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}" >&2
    exit 3
    ;;
esac

:
